# -*- coding: utf-8 -*-
"""Assignment1_MuhammadHarizBinAzaman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpNi5Ip9Xfq4Cy-aROMhAC5VtF2I0nzN
"""

'''
Write a Python program to convert temperatures to and from Celsius and Fahrenheit.

[ Formula : c/5 = f-32/9 [ where c = temperature in celsius and f = temperature in fahrenheit ]

Expected Output :

60°C is 140 in Fahrenheit
45°F is 7 in Celsius
'''

choice = str(input("Choose the type of Temperature you want to convert (C/F): "))

if choice.upper() == 'C':
    # Celsius to Fahrenheit
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}°C is {fahrenheit}°F")

elif choice.upper() == 'F':
    # Fahrenheit to Celsius
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9

'''
Count Even and Odd Numbers

Write a Python program to count the number of even and odd numbers in a series of numbers

Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

Expected Output :

Number of even numbers : 5
Number of odd numbers : 4
'''

numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)
even_count = 0
odd_count = 0

for num in numbers:
    if num % 2 == 0:
        even_count += 1
    else:
        odd_count += 1

print("Number of even numbers:", even_count)
print("Number of odd numbers:", odd_count)

'''
Fibonacci Series Between 0 and 50

Write a Python program to get the Fibonacci series between 0 and 50.

Note : The Fibonacci Sequence is the series of numbers :

0, 1, 1, 2, 3, 5, 8, 13, 21, ....
Every next number is found by adding up the two numbers before it.

Expected Output : 1 1 2 3 5 8 13 21 34
'''

a,b = 0,1
while b<50:
    print(b,end=" ")
    a,b = b,a+b

'''
FizzBuzz Variation

Write a Python program that iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for multiples of five print "Buzz". For numbers that are multiples of three and five, print "FizzBuzz".

Sample Output :

fizzbuzz
1
2
fizz
4
buzz
'''

for i in range(1,51):
    if i%3==0 and i%5==0:
        print("FizzBuzz")
    elif i%3==0:
        print("Fizz")
    elif i%5==0:
        print("Buzz")
    else:
        print(i)

'''
Password Validity Checker

Write a Python program to check the validity of passwords input by users.

Validation :

At least 1 letter between [a-z] and 1 letter between [A-Z].
At least 1 number between [0-9].
At least 1 character from [$#@].
Minimum length 6 characters.
Maximum length 16 characters.
'''

password = input("Create your password: ")

lower = False
upper = False
digit = False
special = False

for char in password:
    if char.islower():
        lower = True
    elif char.isupper():
        upper = True
    elif char.isdigit():
        digit = True
    elif char in '$#@':
        special = True

if len(password) >= 6 and len(password) <= 16 and lower and upper and digit and special:
    print("Password is valid")
else:
    print("Password is not valid")
    print("please follow these rules: ")
    print("At least 1 letter between [a-z] and 1 letter between [A-Z].")
    print("At least 1 number between [0-9].")
    print("At least 1 character from [$#@]")

'''
Dog Age in Dog Years

Write a Python program to calculate a dog's age in dog years.

Note: For the first two years, a dog year is equal to 10.5 human years. After that, each dog year equals 4 human years.

Expected Output:

Input a dog's age in human years: 15
The dog's age in dog's years is 73
'''

dogAge = int(input("Input a dog's age in human years: "))

if dogAge <= 2:
    dogYears = dogAge * 10.5
else:
    dogYears = (21 + (dogAge-2)*4)

print(f"The dog's age in dog's years is {dogYears}")

'''
Astrological Sign Finder

Write a Python program to display the astrological sign for a given date of birth.

Expected Output:

Input birthday: 15
Input month of birth (e.g. march, july etc): may
Your Astrological sign is : Taurus
'''

birthday = int(input("Input birthday: "))
month = input("Input month of birth (e.g. march, july etc): ").lower()

if month == 'december':
    astro_sign = 'Sagittarius' if (birthday < 22) else 'capricorn'
elif month == 'january':
    astro_sign = 'Capricorn' if (birthday < 20) else 'aquarius'
elif month == 'february':
    astro_sign = 'Aquarius' if (birthday < 19) else 'pisces'
elif month == 'march':
    astro_sign = 'Pisces' if (birthday < 21) else 'aries'
elif month == 'april':
    astro_sign = 'Aries' if (birthday < 20) else 'taurus'
elif month == 'may':
    astro_sign = 'Taurus' if (birthday < 21) else 'gemini'
elif month == 'june':
    astro_sign = 'Gemini' if (birthday < 21) else 'cancer'
elif month == 'july':
    astro_sign = 'Cancer' if (birthday < 23) else 'leo'
elif month == 'august':
    astro_sign = 'Leo' if (birthday < 23) else 'virgo'
elif month == 'september':
    astro_sign = 'Virgo' if (birthday < 23) else 'libra'
elif month == 'october':
    astro_sign = 'Libra' if (birthday < 23) else 'scorpio'
elif month == 'november':
    astro_sign = 'scorpio' if (birthday < 22) else 'sagittarius'

print("Your Astrological sign is :",astro_sign)

'''
Chinese Zodiac Sign

Write a Python program to display the sign of the Chinese Zodiac for the given year in which you were born.

Expected Output:

Input your birth year: 1973
Your Zodiac sign : Ox
'''

year = int(input("Input your birth year: "))

zodiac = ["Monkey", "Rooster", "Dog", "Pig", "Rat", "Ox", "Tiger", "Rabbit", "Dragon", "Snake", "Horse", "Goat"]
sign = zodiac[year % 12]
print("Your Zodiac sign :", sign)